name: Build_Huawei_hi3660_KSU_NEXT_Kernel
on:
  workflow_dispatch:
  schedule:
      # Run once at 12:00 on Saturday.. See http://crontab.guru
      - cron: '00 12 * * 6'
  push:
    branches:
      - HEAD
  pull_request:
      branches:
      - HEAD

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "2G"
      CCACHE_HARDLINK: "true"
      KERNEL_CMDLINE: "ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- O=out"
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 100

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Install dependencies
      run: |
        sudo apt-get update -y 
        sudo apt install binutils make python2 libssl-dev flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs bc bison build-essential ccache curl flex g++-9 gcc-9 git git-lfs gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev adb fastboot -y
        git clone https://github.com/Coconutat/ToolChains.git --dept=1 -b linaro_gcc_4.9
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 100
    
    - name: Get Time
      id: get_time
      run: |
        echo "TIME=$(TZ=UTC-8 date +%m%d%H%M )" >> $GITHUB_OUTPUT
        
    - name: Copy KSU base files to kernel
      run: |
        cp  KSU_not_kprobe_base_file/drivers/input/input.c $(pwd)/drivers/input/
        cp  KSU_not_kprobe_base_file/fs/exec.c $(pwd)/fs/
        cp  KSU_not_kprobe_base_file/fs/namespace.c $(pwd)/fs/
        cp  KSU_not_kprobe_base_file/fs/open.c $(pwd)/fs/
        cp  KSU_not_kprobe_base_file/fs/read_write.c $(pwd)/fs/
        cp  KSU_not_kprobe_base_file/fs/stat.c $(pwd)/fs/
        cp  KSU_not_kprobe_base_file/fs/devpts/inode.c $(pwd)/fs/devpts/
        cp  KSU_not_kprobe_base_file/security/selinux/hooks.c $(pwd)/security/selinux/
        
    - name: Build P10 KSU_NEXT_N Kernel
      run: |
       sudo ln -sf /usr/bin/python2.7 /usr/bin/python
       if [ -d include/config ];
        then
         echo "Find config,will remove it"
         rm -rf include/config
       else
        echo "No Config,good."
       fi

       rm -rf KernelSU-Next
       rm -rf drivers/kernelsu
       curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -
       export PATH=$(pwd)/ToolChains/bin/:$PATH
       export ARCH=arm64
       export SUBARCH=arm64
       sudo ln -sf /usr/bin/python2.7 /usr/bin/python
       sudo chmod -R 777 $(pwd)/
       make $KERNEL_CMDLINE Pangu_P10_KSU_NEXT_N_defconfig
       make $KERNEL_CMDLINE -j$(nproc --all)
       tools/mkbootimg --kernel out/arch/arm64/boot/Image.gz --base 0x0 --cmdline "loglevel=4 initcall_debug=n page_tracker=on slub_min_objects=16 unmovable_isolate1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=enforcing buildvariant=user" --tags_offset 0x07A00000 --kernel_offset 0x00080000 --ramdisk_offset 0x07c00000 --header_version 1 --os_version 9 --os_patch_level 2020-09-05  --output Pangu_P10_KSU_NEXT_N-enforcing-${{ steps.get_time.outputs.TIME }}.img
       tools/mkbootimg --kernel out/arch/arm64/boot/Image.gz --base 0x0 --cmdline "loglevel=4 initcall_debug=n page_tracker=on slub_min_objects=16 unmovable_isolate1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=permissive buildvariant=user" --tags_offset 0x07A00000 --kernel_offset 0x00080000 --ramdisk_offset 0x07c00000 --header_version 1 --os_version 9 --os_patch_level 2020-09-05  --output Pangu_P10_KSU_NEXT_N-permissive-${{ steps.get_time.outputs.TIME }}.img

    - name: Upload P10 KSU_NEXT_N Kernel
      uses: actions/upload-artifact@v4
      with:
        name: Pangu_P10_KSU_NEXT_N-kernel-${{ steps.get_time.outputs.TIME }}
        path: "Pangu_P10_KSU_NEXT_N-*.img"

    - name: Build V9 KSU_NEXT_N Kernel
      run: |
        if [ -d include/config ];
         then
          echo "Find config,will remove it"
          rm -rf include/config
        else
          echo "No Config,good."
        fi

        rm -rf KernelSU-Next
        rm -rf drivers/kernelsu
        rm -rf out
        rm -rf Pangu_P10_KSU_NEXT_N-*.img
        curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -
        export PATH=$(pwd)/ToolChains/bin/:$PATH
        export ARCH=arm64
        export SUBARCH=arm64
        sudo ln -sf /usr/bin/python2.7 /usr/bin/python
        sudo chmod -R 777 $(pwd)/
        make $KERNEL_CMDLINE Pangu_V9_KSU_NEXT_N_defconfig
        make $KERNEL_CMDLINE -j$(nproc --all)
        tools/mkbootimg --kernel out/arch/arm64/boot/Image.gz --base 0x0 --cmdline "loglevel=4 initcall_debug=n page_tracker=on slub_min_objects=16 unmovable_isolate1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=enforcing buildvariant=user" --tags_offset 0x07A00000 --kernel_offset 0x00080000 --ramdisk_offset 0x07c00000 --header_version 1 --os_version 9 --os_patch_level 2020-09-05  --output Pangu_V9_KSU_NEXT_N-enforcing-${{ steps.get_time.outputs.TIME }}.img
        tools/mkbootimg --kernel out/arch/arm64/boot/Image.gz --base 0x0 --cmdline "loglevel=4 initcall_debug=n page_tracker=on slub_min_objects=16 unmovable_isolate1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=permissive buildvariant=user" --tags_offset 0x07A00000 --kernel_offset 0x00080000 --ramdisk_offset 0x07c00000 --header_version 1 --os_version 9 --os_patch_level 2020-09-05  --output Pangu_V9_KSU_NEXT_N-permissive-${{ steps.get_time.outputs.TIME }}.img

    - name: Upload V9 KSU_NEXT_N Kernel
      uses: actions/upload-artifact@v4
      with:
        name: Pangu_V9_KSU_NEXT_N-kernel-${{ steps.get_time.outputs.TIME }}
        path: "Pangu_V9_KSU_NEXT_N-*.img"

    - name: Copy Susfs base files to kernel
      run: |
        cp -r KSU_Susfs_base_file/1.5.5/fs/susfs.c $(pwd)/fs/
        cp -r KSU_Susfs_base_file/1.5.5/fs/sus_su.c $(pwd)/fs/
        cp -r KSU_Susfs_base_file/1.5.5/fs/statfs.c $(pwd)/fs/
        cp -r KSU_Susfs_base_file/1.5.5/fs/stat.c $(pwd)/fs/
        cp -r KSU_Susfs_base_file/1.5.5/fs/readdir.c $(pwd)/fs/
        cp -r KSU_Susfs_base_file/1.5.5/fs/proc_namespace.c $(pwd)/fs/
        cp -r KSU_Susfs_base_file/1.5.5/fs/namespace.c $(pwd)/fs/
        cp -r KSU_Susfs_base_file/1.5.5/fs/namei.c $(pwd)/fs/
        cp -r KSU_Susfs_base_file/1.5.5/fs/Makefile $(pwd)/fs/
        cp -r KSU_Susfs_base_file/1.5.5/fs/dcache.c $(pwd)/fs/
        cp -r KSU_Susfs_base_file/1.5.5/fs/proc/cmdline.c $(pwd)/fs/proc/
        cp -r KSU_Susfs_base_file/1.5.5/fs/proc/fd.c $(pwd)/fs/proc/
        cp -r KSU_Susfs_base_file/1.5.5/fs/proc/task_mmu.c $(pwd)/fs/proc/
        cp -r KSU_Susfs_base_file/1.5.5/fs/overlayfs/inode.c $(pwd)/fs/overlayfs/
        cp -r KSU_Susfs_base_file/1.5.5/fs/overlayfs/overlayfs.h $(pwd)/fs/overlayfs/
        cp -r KSU_Susfs_base_file/1.5.5/fs/overlayfs/readdir.c $(pwd)/fs/overlayfs/
        cp -r KSU_Susfs_base_file/1.5.5/fs/overlayfs/super.c $(pwd)/fs/overlayfs/
        cp -r KSU_Susfs_base_file/1.5.5/fs/notify/fdinfo.c $(pwd)/fs/notify/
        cp -r KSU_Susfs_base_file/1.5.5/include/linux/mount.h $(pwd)/include/linux/
        cp -r KSU_Susfs_base_file/1.5.5/include/linux/sched.h $(pwd)/include/linux/
        cp -r KSU_Susfs_base_file/1.5.5/include/linux/sus_su.h $(pwd)/include/linux/
        cp -r KSU_Susfs_base_file/1.5.5/include/linux/susfs.h $(pwd)/include/linux/
        cp -r KSU_Susfs_base_file/1.5.5/include/linux/susfs_def.h $(pwd)/include/linux/
        cp -r KSU_Susfs_base_file/1.5.5/kernel/kallsyms.c $(pwd)/kernel/
        cp -r KSU_Susfs_base_file/1.5.5/kernel/sys.c $(pwd)/kernel/

    - name: Build V9 KSU_NEXT_S Kernel
      run: |
        if [ -d include/config ];
         then
          echo "Find config,will remove it"
          rm -rf include/config
        else
          echo "No Config,good."
        fi

        rm -rf KernelSU-Next
        rm -rf drivers/kernelsu
        rm -rf out
        rm -rf Pangu_V9_KSU_NEXT_N-*.img
        rm -rf kernel_patches
        git clone https://github.com/WildKernels/kernel_patches.git --depth=1 -b main
        curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -
        cp kernel_patches/next/0001-kernel-implement-susfs-v1.5.5-v1.5.7-KSUN-v1.0.8.patch $(pwd)/KernelSU-Next/kernel/
        cd $(pwd)/KernelSU-Next/kernel/
        patch -p1 --forward < 0001-kernel-implement-susfs-v1.5.5-v1.5.7-KSUN-v1.0.8.patch || true
        cd ..
        cd ..
        export PATH=$(pwd)/ToolChains/bin/:$PATH
        export ARCH=arm64
        export SUBARCH=arm64
        sudo ln -sf /usr/bin/python2.7 /usr/bin/python
        sudo chmod -R 777 $(pwd)/
        make $KERNEL_CMDLINE Pangu_V9_KSU_NEXT_S_defconfig
        make $KERNEL_CMDLINE -j$(nproc --all)
        tools/mkbootimg --kernel out/arch/arm64/boot/Image.gz --base 0x0 --cmdline "loglevel=4 initcall_debug=n page_tracker=on slub_min_objects=16 unmovable_isolate1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=enforcing buildvariant=user" --tags_offset 0x07A00000 --kernel_offset 0x00080000 --ramdisk_offset 0x07c00000 --header_version 1 --os_version 9 --os_patch_level 2020-09-05  --output Pangu_V9_KSU_NEXT_S-enforcing-${{ steps.get_time.outputs.TIME }}.img
        tools/mkbootimg --kernel out/arch/arm64/boot/Image.gz --base 0x0 --cmdline "loglevel=4 initcall_debug=n page_tracker=on slub_min_objects=16 unmovable_isolate1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=permissive buildvariant=user" --tags_offset 0x07A00000 --kernel_offset 0x00080000 --ramdisk_offset 0x07c00000 --header_version 1 --os_version 9 --os_patch_level 2020-09-05  --output Pangu_V9_KSU_NEXT_S-permissive-${{ steps.get_time.outputs.TIME }}.img

    - name: Upload V9 KSU_NEXT_S Kernel
      uses: actions/upload-artifact@v4
      with:
        name: Pangu_V9_KSU_NEXT_S-kernel-${{ steps.get_time.outputs.TIME }}
        path: "Pangu_V9_KSU_NEXT_S-*.img"

    - name: Build P10 KSU_NEXT_S Kernel
      run: |
        if [ -d include/config ];
         then
          echo "Find config,will remove it"
          rm -rf include/config
        else
          echo "No Config,good."
        fi

        rm -rf KernelSU-Next
        rm -rf drivers/kernelsu
        rm -rf out
        rm -rf Pangu_V9_KSU_NEXT_N-*.img
        rm -rf kernel_patches
        git clone https://github.com/WildKernels/kernel_patches.git --depth=1 -b main
        curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -
        cp kernel_patches/next/0001-kernel-implement-susfs-v1.5.5-v1.5.7-KSUN-v1.0.8.patch $(pwd)/KernelSU-Next/kernel/
        cd $(pwd)/KernelSU-Next/kernel/
        patch -p1 --forward < 0001-kernel-implement-susfs-v1.5.5-v1.5.7-KSUN-v1.0.8.patch || true
        cd ..
        cd ..
        export PATH=$(pwd)/ToolChains/bin/:$PATH
        export ARCH=arm64
        export SUBARCH=arm64
        sudo ln -sf /usr/bin/python2.7 /usr/bin/python
        sudo chmod -R 777 $(pwd)/
        make $KERNEL_CMDLINE Pangu_P10_KSU_NEXT_S_defconfig
        make $KERNEL_CMDLINE -j$(nproc --all)
        tools/mkbootimg --kernel out/arch/arm64/boot/Image.gz --base 0x0 --cmdline "loglevel=4 initcall_debug=n page_tracker=on slub_min_objects=16 unmovable_isolate1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=enforcing buildvariant=user" --tags_offset 0x07A00000 --kernel_offset 0x00080000 --ramdisk_offset 0x07c00000 --header_version 1 --os_version 9 --os_patch_level 2020-09-05  --output Pangu_P10_KSU_NEXT_S-enforcing-${{ steps.get_time.outputs.TIME }}.img
        tools/mkbootimg --kernel out/arch/arm64/boot/Image.gz --base 0x0 --cmdline "loglevel=4 initcall_debug=n page_tracker=on slub_min_objects=16 unmovable_isolate1=2:192M,3:224M,4:256M printktimer=0xfff0a000,0x534,0x538 androidboot.selinux=permissive buildvariant=user" --tags_offset 0x07A00000 --kernel_offset 0x00080000 --ramdisk_offset 0x07c00000 --header_version 1 --os_version 9 --os_patch_level 2020-09-05  --output Pangu_P10_KSU_NEXT_S-permissive-${{ steps.get_time.outputs.TIME }}.img

    - name: Upload P10 KSU_NEXT_S Kernel
      uses: actions/upload-artifact@v4
      with:
        name: Pangu_P10_KSU_NEXT_S-kernel-${{ steps.get_time.outputs.TIME }}
        path: "Pangu_P10_KSU_NEXT_S-*.img"
